### ISSUE TITLE
Improve zsh hook

### ISSUE THREAD

**Issue by ryuheechul** [teaxyz/cli#281]
Currently tea's zsh hook is below.

```zsh
add-zsh-hook -Uz chpwd(){ source <(tea -Eds) }
```

This seems to cause my shell to keep erasing the shell result every time I run a command (I don't know exactly why yet)

When I run the command below with and without hook I get result below.

```zsh
$ echo "${chpwd_functions[@]}"

_tea_hook _direnv_hook @zinit-scheduler # without tea hook
_tea_hook _direnv_hook # with tea hook
```

I tried this way below instead and it seems to work better.
(pretty much copied from https://github.com/direnv/direnv/blob/f265a7fb1553242a180eee6d1073636e7be0dc8c/internal/cmd/shell_zsh.go#L9-L23)

```zsh
_tea_hook() {
  source <(tea -Eds)
}

typeset -ag chpwd_functions;

if [[ -z "${chpwd_functions[(r)_tea_hook]+1}" ]]; then
  chpwd_functions=( _tea_hook ${chpwd_functions[@]} )
fi
```

Currently I don't have enough zsh knowledge to pinpoint what exactly is the problem and what exactly is the suggestion but reporting it already as I discovered an issue. I will add more information if I can find more.

**Comment by mxcl** [comment]
yikes. Presumably #287 is the problem.

Your solution seems like a great addition even though I need to try fixing the “remove one line” behavior first.

**Comment by ryuheechul** [comment]
Haha yeah. But I wouldn’t care if it’s one line or two lines, three lines. Alternatively you could make the cli to print these line via the cli it self and let people to eval it in their `.zshrc` like

```zsh
eval “(tea hook zsh)”
```

Then you can maintain the one line promise!

**Comment by mxcl** [comment]
0.19.0 in fact does this! Probs for the same reasons you came to.

```sh
source <(tea --magic)
```

In terms of being slow, we intend to rewrite in Rust once we're stable. So for now it may add more slowdown than we'd like (<100ms) but eventually we should be super minimal.

**Comment by ryuheechul** [comment]
Cool for the `0.19.0` update!

So I see that one-liner now changed to below.

```zsh
test -d "$HOME/.tea" && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic --silent)
# from the previous one, `add-zsh-hook -Uz chpwd(){ source <(tea -Eds) }`
```

_after I just got upgraded to 0.19.1 via `sh <(curl https://tea.xyz)`_

However the problem still remains as with the result of `tea --magic --silent` is below.

```zsh
# this file is generated and should not be edited

function command_not_found_handler {
  if [ "$TEA_MAGIC" != 0 -a -x "/home/thisuser/.tea/tea.xyz/v0.19.1/bin"/tea ]; then
    "/home/thisuser/.tea/tea.xyz/v0.19.1/bin"/tea -- $*
  fi
}

add-zsh-hook -Uz chpwd() {
  if [ "$TEA_MAGIC" != 0 -a -x "/home/thisuser/.tea/tea.xyz/v0.19.1/bin"/tea ]; then
    source <("/home/thisuser/.tea/tea.xyz/v0.19.1/bin"/tea --env --keep-going --silent --dry-run=w/trace)
  fi
}

# if the user put tea in eg. /usr/local/bin then don’t pollute their PATH
# if ! tea true 2>&1 >/dev/null; then
  export PATH="/home/thisuser/.tea/tea.xyz/v0.19.1/bin:$PATH"
# fi
```

But then now the logic of adding the hook is hide behind the `source` thanks to `0.19.0`, so fixing this would not requires from user side any more other than updating tea! (as long as there is gonna be fix later)

**Comment by ryuheechul** [comment]
Also as a side note just to let my idea out there, since I just conducted updating tea for the first time (and learned that the way to do it is just to do the same as installing), maybe adding a shortcut flag (or subcommand) like `tea [--]upgrade` could invoke running `sh <(curl https://tea.xyz)` for users - with being transparent on that and giving the choice to continue (unless with explicit flag to just go for it). This would be a quick way to upgrade tea, as long as the domain `tea.xyz`, never changes.

**Comment by mxcl** [comment]
`tea -S +tea.xyz` does in fact upgrade tea (tea is a pkg too).

The “deleting line” issue should be fixed BTW.

I'm looking at improving the hook per your suggestion RN 👊🏻

**Comment by ryuheechul** [comment]
Thanks and can't wait to see the improvements!

If the "deleting line" is referring to below
> This seems to cause my shell to keep erasing the shell result every time I run a command

(I also assume the fix is coming from https://github.com/teaxyz/cli/commit/c908653b66df4a8f89b654fd357b5fb2bbfe977b?)

I just installed tea (0.22.1) to a new macOS machine and I still see the erasing line behaviour.

**However**, this time I found a better clue. 

When I comment this line out, https://github.com/ryuheechul/dotfiles/blob/a3d104324a49662f567ff9f8f44c2ead19ffb75c/zsh/my_addons/znap#L17, this behaviour no longer happens.

Why I believe that's the line of the issue?
because I see not only stdout gets erase but I also see these error messages
```zsh
.znap.prompt.precmd:7: no such file or directory:
.znap.prompt.precmd:8: no such file or directory:
```

And I believe it's something to do with this - https://github.com/marlonrichert/zsh-snap/blob/4a5b447bc4e43810fbfd931bae4c1be11a9ffdc9/functions/.znap.prompt#L19

However when I manually improve the hook initialization to following to test, "erasing behavior" no longer happens.

```diff
diff --git a/source-tea-old b/source-tea-new
index b1f05ce..716c1c1 100644
--- a/source-tea-old
+++ b/source-tea-new
@@ -1,19 +1,25 @@
 # vim: set ft=zsh:
 
-add-zsh-hook -Uz chpwd() {
+_tea_hook() {
   if [ "${TEA_MAGIC:-}" != 0 -a -x "/Users/user/.tea/tea.xyz/v*/bin"/tea ]; then
     source <("/Users/user/.tea/tea.xyz/v*/bin"/tea +tea.xyz/magic -Esk --chaste env)
   fi
 }
 
+typeset -ag chpwd_functions;
+
+if [[ -z "${chpwd_functions[(r)_tea_hook]+1}" ]]; then
+  chpwd_functions=( _tea_hook ${chpwd_functions[@]} )
+fi
+
 # if the user put tea in eg. /usr/local/bin then don’t pollute their PATH
 # we check for `tea --prefix` due to `gitea` being `tea` when installed with `brew`
 if ! command -v tea 2>&1 >/dev/null || ! tea --prefix 2>&1 >/dev/null; then
   export PATH="/Users/user/.tea/tea.xyz/v*/bin:$PATH"
 fi
 
 function command_not_found_handler {
   if [ "${TEA_MAGIC:-}" != 0 -a -x "/Users/user/.tea/tea.xyz/v*/bin"/tea ]; then
     "/Users/user/.tea/tea.xyz/v*/bin"/tea -- $*
   fi
 }
```
(Again I don't know enough to know clearly about why this works but not the other)

So if the improvement is going to be similar to this way, then I believe it will probably fix it!

**Comment by ryuheechul** [comment]
@mxcl just upgraded to 0.22.3 and it works like a charm, thank you!
